Pedidos/urls.py
#region URLS APP
# Cuando se crea la aplicación el framework no crea este archivo.
# Hay que crearlo a mano.
# La idea es que cada aplicación tenga su propio archivo de urls,
# para que esta sea lo mas independiente posible del proyecto y
# pueda ser reutilizada en otros proyectos.
# Este archivo de urls debe ser importado en /Proyecto/urls.py
# 
#endregion

#importo "path" desde django
from django.urls import path

#Importo el archivo de vistas de la aplicación
from Pedidos import views

#creo la lista con las urls en las que van a estar TODAS las urls
#de la aplicación "Pedidos"
urlpatterns = [
    path('menu', views.menuPrincipal, name='Menu'),

    #region Proveedores
    path('proveedores', views.proveedores, name='Proveedores'),
    path('provnuevo', views.provNuevo, name='provnuevo'),
    path('provEditar/<int:id>', views.provEditar, name='provEditar'),
    path('provBorrar/<int:id>', views.provBorrar, name='provBorrar'),
    #endregion

    #region Cervezas
    path('cervezas', views.cervezas, name='cervezas'),
    path('cervNuevo', views.cervNuevo, name='cervNuevo'),
    path('cervEditar/<int:id>', views.cervEditar, name='cervEditar'),
    path('cervBorrar/<int:id>', views.cervBorrar, name='cervBorrar'),
    #endregion    

    #region Pedidos
    path('pedidos', views.pedidos, name="Pedidos"),
    path('pedidoNuevo/<int:idP>', views.pedidosNuevo, name='pedidoNuevo'),
    path('borrarPedido/<int:idPedido>', views.pedidoBorrar, name='borrarPedido'),
    #endregion
    
    #Ingresos
    path('ingresos', views.ingresosListado, name='IngresosList'),
    path('crearIngreso/<int:idPedido>', views.crearIngreso, name='crearIngreso'),
    path('listarIngresos', views.listIngresos, name='listarIngresos')
]

# Argumentos de path
# El primer argumento es la url
# El segundo argumento es la Vista (controlador) que procesa la petición
# El tercer argumento es el nombre por el cual se va a hacer referencia
#    desde los archivos html #

khronos/urls.py
from django.contrib import admin
from django.urls import path, include



#Acá se especifican las urls
urlpatterns = [
    path('idmin/', admin.site.urls),

    #Importo urls de aplicación Pedidos
    path('', include('Pedidos.urls')),

    path('', include('Usuarios.urls')),

    path('accounts/', include('django.contrib.auth.urls'))
]

Pedidos/models.py
from django.db import models
from django.contrib.auth.models import User

from django.core.validators import MinValueValidator


# Create your models here.
#region Comentarios
# Las clases dentro de este modulo representan los modelos.
# Todos los modelos deben heredar de "models.Model". Esto
# le permite acceder a las funcionalidades del framework.

# Al crear las clases, si no se indica un campo "id", django crea automáticamente
# un campo "id", entero, autoincrement, primaryKey, etc...#

# 
# Una vez creados los modelos se ejecuta el comando
# "python manage.py makemigrations". Esto crea el
# archivo de migraciones en la carpeta "migrations"
# 
# Luego ejecutar "python manage.py migrate"
# Esto hace que el framework cree las tablas
# en la base de datos
#endregion

class Proveedor(models.Model):
    nombre      = models.CharField(max_length=(200), unique=True)
    domicilio   = models.CharField(max_length=(200))
    telefono    = models.CharField(max_length=(50))
    email       = models.EmailField()

    def __str__(self):
        return self.nombre



class Cerveza(models.Model):
    nombre = models.CharField(max_length=200, unique=True)
    proveedor = models.ManyToManyField(Proveedor)

    def __str__(self):
        return self.nombre



class Pedido(models.Model):
    fecha = models.DateField(auto_now_add=True)
    usuario = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.DO_NOTHING)
    cerveza = models.ManyToManyField(Cerveza, through='LineaPedido')
    entregado = models.BooleanField(default=False)


class LineaPedido(models.Model):
    """Esta Clase representa la relacion N a N entre Pedidos y Cervezas.
    Es en esta clase donde se registran las cantidades Pedidas,
    Entregadas y Pendientes de un pedido"""
    cantidad = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    entregado = models.PositiveIntegerField(default=0, blank=True, null=True)
    pendiente = models.PositiveIntegerField(default=0, blank=True, null=True)
    cerveza = models.ForeignKey(Cerveza, on_delete=models.CASCADE)
    pedido = models.ForeignKey(Pedido, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.cerveza)



class Ingreso(models.Model):
    pedido = models.OneToOneField(Pedido, on_delete=models.CASCADE)
    numeroRemito = models.PositiveIntegerField(unique=True)
    fechaIngreso = models.DateField(auto_now=True)
    fechaRemito = models.DateField()



class Barril(models.Model):
    ingreso = models.ForeignKey(Ingreso, on_delete=models.CASCADE)
    numBarril = models.PositiveIntegerField()

Pedidos/forms.py
from django.forms import ModelForm
from .models import Proveedor, Cerveza
#Pedido, LineaPedido

# Ver Usuarios/forms.py

# Este formulario lo importo en "views.py" para instanciarlo
# y pasárselo en el context al controlador que renderiza
# el template de Proveedores. De ese modo puedo mostrar
# el formulario para crear proveedores.
class frProveedor(ModelForm):
    class Meta:
        model = Proveedor

        fields = '__all__'

class frCerveza(ModelForm):
    class Meta:
        model = Cerveza
        fields = '__all__'


#region PEDIDOS
""" class frmPedido(ModelForm):
    class Meta:
        model = Pedido
        fields = [
            'usuario',
            'proveedor'
        ]


class frmLineaPedido(ModelForm):
    class Meta:
        model = LineaPedido
        fields = [
            'cerveza',
            'cantidad'
        ] """

#endregion PEDIDOS

Pedidos/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Importo formularios
from .forms import frProveedor, frCerveza

from .models import Pedido, Proveedor, Cerveza, Ingreso, Barril
# Create your views here.
# En Django (MTV) las vistas son los controladores de MVC
# Cada función dentro de este módulo, representa un controlador


# El framework reconoce automaticamente la carpeta "templates".
# Solo indico la subcarpeta/archivo.html

@login_required
def menuPrincipal(request):
    return render(request, 'Pedidos/menu.html')


#region Controladores Proveedores 
@login_required
def proveedores(request):
                 #No es un error, es problema del ide
    proveedores = Proveedor.objects.all()
    return render(request, 'Pedidos/proveedores.html', {'proveedores':proveedores})


@login_required
def provNuevo(request):

    formulario = frProveedor()

    if request.method == 'POST':
        frpost = frProveedor(request.POST)
        if frpost.is_valid():
            frpost.save()
            return redirect('/proveedores')
        else:
            for mensaje in frpost.errors:
                messages.error(request, frpost.errors[mensaje])
                return render(request, 'Pedidos/proveedoresForm.html', {'formProveedor': frpost, 'titulo':'Nuevo Proveedor'})
    else:
        return render(request, 'Pedidos/proveedoresForm.html', {'formProveedor': formulario, 'titulo':'Nuevo Proveedor'})


@login_required
def provEditar(request, id):
    provID = Proveedor.objects.get(pk=id)
    frEditar = frProveedor()
    if request.method == 'GET':
        frEditar = frProveedor(instance=provID)
        return render(request, 'Pedidos/proveedoresForm.html', {'formProveedor':frEditar, 'titulo':'Editar Proveedor'})
    else:
        frEditar = frProveedor(request.POST, instance=provID)

        if frEditar.is_valid():
            frEditar.save()
        else:
            for mensaje in frEditar.errors:
                messages.error(request, frEditar.errors[mensaje])
                return render(request, 'Pedidos/proveedoresForm.html', {'formProveedor': frEditar, 'titulo':'Editar Proveedor'})
        
        return redirect('/proveedores')


@login_required
def provBorrar(request, id):
    #return HttpResponse('ID Seleccionado: {}'.format(id))
    provID = Proveedor.objects.get(pk=id)
    provID.delete()
    return redirect('/proveedores')

#endregion Proveedores


#region Cervezas
@login_required
def cervezas(request):
    cs = Cerveza.objects.all()
    #region
    # cs es un "QuerySet", un iterable...
    # Cada elemento de "cs" representa un objeto de tipo Cerveza.
    # Cada Cerveza tiene el campo "proveedor", que es un querySet,
    # El campo proveedor es una colección ce objetos Proveedor.
    # Le paso al Template "cs" para listar las cervezas y sus
    # Proveedores.

    # Para entender el funcionamiento de QuerySet
    # https://docs.djangoproject.com/en/3.1/topics/db/examples/many_to_many/

    # Ojo, en el template no puedo usar paréntesis en los métodos
    # por ejemplo "all()"
    #endregion
    return render(request, 'Pedidos/cervezas.html', {'cervezas':cs})


@login_required
def cervNuevo(request):
    formulario = frCerveza()

    if request.method == 'POST':
        form = frCerveza(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/cervezas')
        else:
            for mensaje in form.errors:
                messages.error(request, form.errors[mensaje])
                return render(request, 'Pedidos/cervezasForm.html', {'formCerveza': form, 'titulo':'Nueva Cerveza'})
    else:
        return render(request, 'Pedidos/cervezasForm.html', {'formCerveza':formulario, 'titulo':'Nueva Cerveza'})


@login_required
def cervEditar(request, id):
    cervEdit = Cerveza.objects.get(pk=id)
    frEditar = frCerveza()
    if request.method == 'GET':
        frEditar = frCerveza(instance=cervEdit)
        return render(request, 'Pedidos/cervezasForm.html', {'formCerveza':frEditar, 'titulo':'Editar Cerveza'})
    else:
        frEditar = frCerveza(request.POST, instance=cervEdit)

        if frEditar.is_valid():
            frEditar.save()
        else:
            for mensaje in frEditar.errors:
                messages.error(request, frEditar.errors[mensaje])
                return render(request, 'Pedidos/cervezasForm.html', {'formCerveza': frEditar, 'titulo':'Editar Cerveza'})
        
        return redirect('/cervezas')


@login_required
def cervBorrar(request, id):
    #return HttpResponse('Cervezas Borrar id: {}'.format(id))
    cervDel = Cerveza.objects.get(pk=id)
    cervDel.delete()
    return redirect('/cervezas')

#endregion Cervezas


#region Pedidos
@login_required
def pedidos(request):
    ctxPedidos = {
        'proveedores': Proveedor.objects.all(),
        'lstPedidos' : Pedido.objects.all()
    }
    
    return render(request, 'Pedidos/pedidosListado.html', ctxPedidos)



@login_required
def pedidosNuevo(request, idP):
    if request.method == "GET":
        id = idP
        ctxt = {
            'prv' : Proveedor.objects.get(pk=id)
        }
        return render(request, 'Pedidos/pedidosNuevo.html', ctxt)
    
    elif request.method == 'POST':
        usuario = request.user
        proveedor = Proveedor.objects.get(pk=idP)
        #cerevzas = proveedor.cerveza_set.all()
        
        #Creo objeto pedido Pedido
        pedido = Pedido()
        pedido.usuario = usuario
        pedido.proveedor = proveedor
        pedido.save()

        lstCerv = request.POST.getlist('lineasCerv')
        lstCant = request.POST.getlist('lineaCant')
        
        for i in range(len(lstCerv)):
            """ print(str(lstCerv[i])+" : "+str(lstCant[i]))
            print(" ") """

            pedido.cerveza.add(Cerveza.objects.get(pk=lstCerv[i]), through_defaults={'cantidad':lstCant[i]})

        return redirect('/pedidos')



@login_required
def pedidoBorrar(request, idPedido):
    pedido = Pedido.objects.get(pk=idPedido)
    if pedido.entregado:
        return HttpResponse("No se puede borrar un pedido entregado. no no no señor!")
    else:
        for linea in pedido.lineapedido_set.all():
            linea.delete()
        pedido.delete()
        return redirect('/pedidos')

@login_required
def ingresosListado(request):
    cntxt = {
        'pedidos' : Pedido.objects.all()
    }
    return render(request, 'Pedidos/ingresos.html', cntxt)



def crearIngreso(request, idPedido):
    """Procesa El Ingreso De Un Pedido"""

    # Pedido Seleccionado
    pedido = Pedido.objects.get(pk=idPedido)
    
    # Lineas Del Pedido Seleccionado
    lineas = pedido.lineapedido_set.all()

    # Lista Con los valores de los input de "Cantidad Recibida"
    lstCantRec = request.POST.getlist('recibido')

    # Lista con los valores de numero de Barril
    lstBarriles = request.POST.getlist('barriles')

    # Si la peticion es por GET muestra la grilla para indicar las cantidades
    # que se reciben
    if request.method == 'GET':
        
        ctxt = {
            'pedido' : pedido,
            'lineas': lineas
        }

        return render(request, 'Pedidos/pedidoTablaIngreso.html', ctxt)
    
    # Si la peticion es por POST y se reciben valores en la lista 'recibido'
    # muestra la pantalla para indicar el numero de barril
    # por cada cerveza recibida
    elif request.method == 'POST' and len(lstCantRec)!=0:
        
        lstCerv = []

        # En un rango de la longitud = a la cantidad de elementos en "lstCantRec"
        for i in range(len(lstCantRec)):
            # En un rango de la longitud = a cada uno de los elementos de "lstCantRec"
            for c in range(int(lstCantRec[i])):
                # Se agrega la i° (i definida en el primer 'for') linea de pedido
                # a la lista "lstCerv"
                lstCerv.append(lineas[i])

        contexto = {
            'lstCerv':lstCerv,
            # Envio las cantidades al siguiente template ya que
            # en ese no van a existir
            'cantidades': lstCantRec
            }
        
        return render(request, 'Pedidos/pedidoBarriles.html', contexto)


    # Si la peticion es por POST y se reciben valores en la lista 'barriles'
    # se crea la Recepcion, el Pedido cambia de estado a "recibido",
    # y se crean un barril por cada cantidad recibida.
    elif request.method == 'POST' and len(lstBarriles)!=0:
        #Creo Un Ingreso
        ingreso = Ingreso()

        #Cambia el estado del pedido a "Entregado"
        pedido.entregado = True

        # Relaciono el Ingreso con el Pedido
        ingreso.pedido = pedido

        # Asigno al ingreso el numero de remito
        ingreso.numeroRemito = int(request.POST.get('remito'))

        # Asigno al ingreso Fecha De Remito
        ingreso.fechaRemito = request.POST.get('fecha')

        # Guardo el ingreso 
        ingreso.save()

        # Recibo las cantidades ingresadas en el template en el
        # input "hidden"
        cantidades = request.POST.getlist('cant')

        # En esta lista se guardan lineas de pedido. Cada linea se guarda
        # tantas veces como la cantidad recibida indique. La uso para
        # instanciar un barril por cada linea en la lista.
        lineaBarril = []

        # Asigno a cada linea la cantidad recibida
        # Itero tantas veces como lineas tenga el pedido
        for i in range(len(lineas)):
            # A la i° linea le asigno el valor de la i° cantidad
            lineas[i].entregado = int(cantidades[i])

            # Calculo la cantidad del campo "pendiente" para cada linea
            lineas[i].pendiente = lineas[i].cantidad - lineas[i].entregado

            # Guardo los cambios
            lineas[i].save()
            
            # Agrego en la lista "lineaBarril" cada linea, tantas veces como lo

Pedidos/templates/Pedidos/cervezas.html
{% extends 'Pedidos/menu.html' %}

{%block principal%}

    <!-- Contenedor De Toda La Página -->
    <div class="container-fluid my-3 center">
        
        <!-- Encabezado De la Grilla -->
        <div class="row shadow">
            <span class="col-6 h3">Cervezas</span>

            <a class="btn btn-success ml-auto" href="{% url 'cervNuevo' %}"><span>Nueva Cerveza</span></a>
        </div> <!-- Fin Encabezado De la Grilla -->

        <!-- Tabla Grilla -->
        <table class="table-sm table-responsive table-hover my-2">
            <thead class="table-dark bg-secondary">
                <tr>
                    <th class="text-center" scope="col">#</th>
                    <th class="text-center" scope="col">Nombre</th>
                    <th class="text-center" scope="col">Proveedor</th>
                </tr>
            </thead>

            <tbody>
                
                <!--Itero sobre cada objeto de cervezas que es el querySet-->
                {% for c in cervezas|dictsort:'id' %}
                    
                    <!--Itero sobre cada objeto proveedor de "cerveza"-->
                    {% for p in c.proveedor.all %}
                        <tr>
                            <!--Imprimo el campo "id" de la cerveza-->
                            <td scope="row">{{c.id}}</td>

                            <!--Imprimo el campo "nombre" de la cerveza-->
                            <td> {{c.nombre}} </td>

                            <!--Imprimo el campo "nombre" del Proveedor-->
                            <td> {{p.nombre}} </td>
                            <td class="text-center">
                                
                                <!--Editar-->
                                <a href="{% url 'cervEditar' c.id %}">
                                    <i class="material-icons text-warning" data-toggle="tooltip" title="Editar">&#xE254;</i>
                                </a>

                                <!--Borrar. Despues hay que cambiarlo para Deshabilitar en vez de borrar-->
                                <form action="{% url 'cervBorrar' c.id %}" method="POST" class="d-inline frborrar">
                                    {% csrf_token %}
                                    <button type="submit" class="btn" id="borrar">
                                        <i class="material-icons text-danger" data-toggle="tooltip" title="Borrar">&#xE872;</i>
                                    </button>
                                </form>
                                
                            </td>
                        </tr>
                    {% endfor %}
                    
                {% endfor %}
                
            </tbody>

        </table> <!-- Fein Tabla Grilla -->

    </div> <!-- Fin Contenedor De Toda La Página -->

{%endblock%}


{% block jquery %}
<script>
        
    $(document).ready(function(){

        $(".frborrar").submit(function(e){
            e.preventDefault(e);
            var ruta = $(this).attr('action');

            //Acá uso el plugin "JQUERY-CONFIRM"
            $.confirm({
                theme: 'bootstrap',
                title: 'BORRAR CERVEZA!',
                content: 'Esta Acción No Se Puede Revertir',
                buttons: {
                    //Primer boton
                    danger:{
                        text:'SI',
                        btnClass:' btn-danger ',
                        action: function(){
                            window.location.href=ruta;
                        }
                    },
                    //Segundo boton
                    info:{
                        text: 'No',
                        btnClass: 'btn-info',
                        action: function(){
                            this.close();
                        }
                    }
                }
            });
        });

    });
</script>
{% endblock jquery %}
    

Pedidos/templates/Pedidos/cervezasForm.html
{% extends 'Pedidos/menu.html' %}

{% block principal %}

    {% load crispy_forms_tags %}

    <div id="Nuevo">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="modal-header">						
                        <h4 class="modal-title">{{titulo}}</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button-->
                    </div>
                    <div class="modal-body">					
                        
                        {{ formCerveza | crispy }}
                                            
                    </div>
                    <div class="modal-footer">
                        
                        <input type="submit" class="btn btn-success" value="Aceptar">
                        <a href="{% url 'cervezas' %}" class="btn btn-danger">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Pedidos/templates/Pedidos/ingresoListado.html
{% extends 'Pedidos/menu.html' %}


{% block principal %}

    {% for key, value in ingresos.items %}
        <div class="card border-secondary mt-4 mb-4">
            <div class="card-header">
                <p class="">
                    <span class="mr-4">Ingreso: {{key.id}}</span>
                    <span class="mr-4">Fecha De Ingreso: {{key.fechaIngreso}}</span> | 
                    <span class="mr-4">Remito N°: {{key.numeroRemito}}</span>
                    <span class="mr-4">Fecha De Remito: {{key.fechaRemito}}</span>
                </p>

                <hr>
                
                <p>
                    <span class="mr-4">Pedido: {{key.pedido.id}} </span>
                    <span class="mr-4">Proveedor: {{key.pedido.proveedor}} </span>
                    <span class="mr-4">Fecha De Pedido: {{key.pedido.fecha}} </span>
                    <span class="mr-4">Usuario: {{key.pedido.usuario}} </span>
                </p>
            </div>
            
            <div class="card-body">
                <div class="row">
                    <div class="col-xs-2 col-md-6">
                        <h5 class="card-title">Cervezas</h5>
                        <ul class="list-group">
                            {% for v in value %}
                                <li class="list-group-item"> {{v}} </li>    
                            {% endfor %}    
                        </ul>
                    </div>

                    <div class="col-xs-2 col-md-6">
                        <h5 class="card-title">Barriles</h5>
                        <ul class="list-group">
                            {% for barril in key.barril_set.all %}
                                <li class="list-group-item"> {{barril.numBarril}} </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                
            </div>
        </div>
    {% endfor %}
{% endblock principal %}


{% block jquery %}
    <script>

    </script>
{% endblock jquery %}

Pedidos/templates/Pedidos/ingresos.html
{% extends 'Pedidos/menu.html' %}


{% block principal %}
   
<body>
    <!-- Contenedor De Toda La Página -->
    <div class="container-fluid my-3 center">
        
        <!-- Encabezado De la Grilla -->
        <div class="row shadow">
            <span class="col-6 h3">Ingresos</span>

            
        </div> <!-- Fin Encabezado De la Grilla -->

        <!-- Tabla Grilla -->
        <table class="table-sm table-responsive table-hover my-2">
            <thead class="table-dark bg-secondary">
                <tr>
                    <th class="text-center" scope="col"># Pedido</th>
                    <th class="text-center" scope="col">Usuario</th>
                    <th class="text-center" scope="col">Fecha</th>
                    <th class="text-center" scope="col">Proveedor</th>
                    <th class="text-center" scope="col">Acciones</th>
                </tr>
            </thead>

            <tbody>
                
                {% for p in pedidos %}
                    
                    {% if  not p.entregado %}
                        <tr><!--Fila 1-->
                            <td scope="row" class="text-center">{{p.id}}</td>
                            <td>{{p.usuario}}</td>
                            <td class="text-center">{{p.fecha}}</td>
                            <td>{{p.proveedor}}</td>
                            <td class="text-center">
                                <a href="{% url 'crearIngreso' p.id %}" class="btn btn-sm btn-outline-success">Ingresar Pedido</a>
                            </td>
                        </tr>
                    {% endif %}
                        
                {% endfor %}
            </tbody>

        </table> <!-- Fein Tabla Grilla -->

    </div> <!-- Fin Contenedor De Toda La Página -->

 <!-------------------------------------------------------------------------------------------------------------------------
                        Acá están las ventanas modales para Editar y Borrar
 -------------------------------------------------------------------------------------------------------------------------->

	<!-- EDITAR Modal HTML -->
	<div id="tablaIngreso_{{p.id}}" class="modal fade">
		<div class="modal-dialog modal-xl">
			<div class="modal-content">
				<form>
					<div class="modal-header">						
						<h4 class="modal-title">Ingreso De Pedido</h4>
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					</div>
					<div class="modal-body">					
						<table class="table-sm table-responsive table-hover my-2">
                            <thead class="table-dark bg-secondary">
                                <tr>
                                    <th class="text-center" scope="col"># Pedido</th>
                                    <th class="text-center" scope="col">Usuario</th>
                                    <th class="text-center" scope="col">Fecha</th>
                                    <th class="text-center" scope="col">Proveedor</th>
                                    <th class="text-center" scope="col">Tipo De Cerbeza</th>
                                    <th class="text-center" scope="col">Cantidad</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr><!--Fila 1-->
                                    <td scope="row" class="text-center">1</td>
                                    <td>Thomas Hardy</td>
                                    <td class="text-center">25/08/1820</td>
                                    <td>Astor</td>
                                    <td>Porter</td>
                                    <td class="text-center">
                                        <input class="form-control" type="text" placeholder="">
                                    </td>
                                    
                                </tr>
                            </tbody>
                        </table>
					</div>
					<div class="modal-footer">
                        <!--EL BOTON DE ACEPTAR SE DEBE CAMBIAR A SUBMIT CUANDO SE IMPLEMENTE-->
                        <input type="button" class="btn btn-info" value="Aceptar">
						<input type="button" class="btn btn-danger" data-dismiss="modal" value="Cancelar">
					</div>
				</form>
			</div>
		</div>
	</div>

</body>
{% endblock principal %}


{% block jquery %}
    
{% endblock jquery %}
    

Pedidos/templates/Pedidos/pedidoBarriles.html
{% extends 'Pedidos/menu.html' %}


{% block principal %}   
<div id="tablaIngreso">
    <h4 class="modal-title text-center mt-4">Registrar Barriles</h4>
    
    <form method="POST">
        {% csrf_token %}
        <div class="modal-body">
            <div class="row align-self-center">
                <input type="number" min="1" id="remito" name="remito" class="form-control col-md-4 mr-4" placeholder="Numero De Remito">
                <input type="date" name="fecha" class="form-control col-md-4" placeholder="Fecha De Remito ml-2">
            </div>

            <table class="table-sm table-responsive table-hover my-2">
                <thead class="table-dark bg-secondary">
                    <tr>
                        <th class="text-center" scope="col">Tipo De Cerveza</th>
                        <th class="text-center" scope="col">Barril</th>
                    </tr>
                </thead>
                <tbody>
                    
                    
                    {% for linea in lstCerv %}
                        <tr>
                            <td>{{linea.cerveza}}</td>
                            <td class="text-center">
                                <input name="barriles" class="form-control cantRec" type="number" min="1" required placeholder="Numero De Barril">
                            </td>
                        </tr>
                    {% endfor %}
                    {% for v in cantidades %}
                        <input type="hidden" name="cant" value="{{v}}">
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
        <div class="modal-footer">
            <!--EL BOTON DE ACEPTAR SE DEBE CAMBIAR A SUBMIT CUANDO SE IMPLEMENTE-->
            <input type="submit" class="btn btn-info" value="Aceptar">
            <a href="{% url 'Pedidos' %}" class="btn btn-danger">Cancelar</a>
        </div>
    </form>
</div> 

{% endblock principal %}


{% block jquery %}
    <script>

    </script>
{% endblock jquery %}

Pedidos/templates/Pedidos/proveedoresForm.html
{% extends 'Pedidos/menu.html' %}

{% block principal %}

    {% load crispy_forms_tags %}

    <div id="Nuevo">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <form action="" method="POST">
                    {% csrf_token %}
                    <div class="modal-header">						
                        <h4 class="modal-title">{{titulo}}</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button-->
                    </div>
                    <div class="modal-body">					
                        
                        {{ formProveedor | crispy }}
                                            
                    </div>
                    <div class="modal-footer">
                        
                        <input type="submit" class="btn btn-success" value="Aceptar">
                        <a href="{% url 'Proveedores' %}" class="btn btn-danger">Cancelar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}